alter table if exists scalping_strategy_settings
    add column if not exists regime_auto_enabled boolean not null default true,
    add column if not exists allow_trend_trades boolean not null default true,
    add column if not exists allow_range_trades boolean not null default true,
    add column if not exists allow_breakout_trades boolean not null default true,
    add column if not exists allow_counter_trend_trades boolean not null default false,
    add column if not exists chaos_block_threshold double precision not null default 62.0,
    add column if not exists squeeze_threshold double precision not null default 72.0,
    add column if not exists trend_min_score double precision not null default 58.0,
    add column if not exists pullback_max_depth_pct double precision not null default 0.90,
    add column if not exists pullback_entry_buffer_pct double precision not null default 0.30,
    add column if not exists trend_tp_pct double precision not null default 0.28,
    add column if not exists trend_sl_pct double precision not null default 0.16,
    add column if not exists trend_break_even_pct double precision not null default 0.12,
    add column if not exists trend_max_hold_sec integer not null default 420,
    add column if not exists range_min_score double precision not null default 52.0,
    add column if not exists range_entry_from_low_pct double precision not null default 0.55,
    add column if not exists range_exit_to_mid_pct double precision not null default 0.50,
    add column if not exists range_tp_pct double precision not null default 0.16,
    add column if not exists range_sl_pct double precision not null default 0.12,
    add column if not exists range_max_hold_sec integer not null default 180,
    add column if not exists breakout_min_score double precision not null default 61.0,
    add column if not exists breakout_volume_factor double precision not null default 1.20,
    add column if not exists breakout_tp_pct double precision not null default 0.34,
    add column if not exists breakout_sl_pct double precision not null default 0.18,
    add column if not exists max_spread_pct double precision not null default 0.12,
    add column if not exists min_atr_pct double precision not null default 0.03,
    add column if not exists max_atr_pct double precision not null default 0.80,
    add column if not exists min_volume_ratio double precision not null default 0.75,
    add column if not exists min_risk_reward double precision not null default 1.05,
    add column if not exists cooldown_after_stop_sec integer not null default 45,
    add column if not exists cooldown_after_exit_sec integer not null default 12,
    add column if not exists max_consecutive_stops integer not null default 3,
    add column if not exists reentry_lock_sec integer not null default 18,
    add column if not exists emergency_chaos_exit_enabled boolean not null default true,
    add column if not exists partial_exit_enabled boolean not null default true,
    add column if not exists partial_exit_pct double precision not null default 0.50,
    add column if not exists partial_exit_trigger_pct double precision not null default 0.18,
    add column if not exists use_intrabar_confirmation boolean not null default true,
    add column if not exists micro_window_size integer not null default 8;
