CREATE TABLE exchange_settings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id     BIGINT                                  NOT NULL,
    exchange    VARCHAR(32)                             NOT NULL,
    network     VARCHAR(16)                             NOT NULL,
    api_key     VARCHAR(256)                            NOT NULL,
    api_secret  VARCHAR(256)                            NOT NULL,
    passphrase  VARCHAR(256),
    sub_account VARCHAR(128),
    enabled     BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_exchange_settings PRIMARY KEY (id)
);

ALTER TABLE exchange_settings
    ADD CONSTRAINT ux_exchange_settings_chat_exchange_network UNIQUE (chat_id, exchange, network);

CREATE INDEX ix_exchange_settings_chat ON exchange_settings (chat_id);

CREATE INDEX ix_exchange_settings_exchange ON exchange_settings (exchange);